package net.minecraft.server;

public class AetherRecipes
{
    public AetherRecipes() {
        ModLoader.addRecipe(new ItemStack(AetherItems.PickHolystone, 1), new Object[] { "ZZZ", " Y ", " Y ", 'Z', AetherBlocks.Holystone, 'Y', AetherItems.Stick });
        ModLoader.addRecipe(new ItemStack(AetherItems.AxeHolystone, 1), new Object[] { "ZZ", "ZY", " Y", 'Z', AetherBlocks.Holystone, 'Y', AetherItems.Stick });
        ModLoader.addRecipe(new ItemStack(AetherItems.ShovelHolystone, 1), new Object[] { "Z", "Y", "Y", 'Z', AetherBlocks.Holystone, 'Y', AetherItems.Stick });
        ModLoader.addRecipe(new ItemStack(AetherItems.SwordHolystone, 1), new Object[] { "Z", "Z", "Y", 'Z', AetherBlocks.Holystone, 'Y', AetherItems.Stick });
        ModLoader.addRecipe(new ItemStack(AetherItems.PickZanite, 1), new Object[] { "ZZZ", " Y ", " Y ", 'Z', AetherItems.Zanite, 'Y', AetherItems.Stick });
        ModLoader.addRecipe(new ItemStack(AetherItems.AxeZanite, 1), new Object[] { "ZZ", "ZY", " Y", 'Z', AetherItems.Zanite, 'Y', AetherItems.Stick });
        ModLoader.addRecipe(new ItemStack(AetherItems.ShovelZanite, 1), new Object[] { "Z", "Y", "Y", 'Z', AetherItems.Zanite, 'Y', AetherItems.Stick });
        ModLoader.addRecipe(new ItemStack(AetherItems.SwordZanite, 1), new Object[] { "Z", "Z", "Y", 'Z', AetherItems.Zanite, 'Y', AetherItems.Stick });
        ModLoader.addRecipe(new ItemStack(AetherItems.PickGravitite, 1), new Object[] { "ZZZ", " Y ", " Y ", 'Z', AetherBlocks.EnchantedGravitite, 'Y', AetherItems.Stick });
        ModLoader.addRecipe(new ItemStack(AetherItems.AxeGravitite, 1), new Object[] { "ZZ", "ZY", " Y", 'Z', AetherBlocks.EnchantedGravitite, 'Y', AetherItems.Stick });
        ModLoader.addRecipe(new ItemStack(AetherItems.ShovelGravitite, 1), new Object[] { "Z", "Y", "Y", 'Z', AetherBlocks.EnchantedGravitite, 'Y', AetherItems.Stick });
        ModLoader.addRecipe(new ItemStack(AetherItems.SwordGravitite, 1), new Object[] { "Z", "Z", "Y", 'Z', AetherBlocks.EnchantedGravitite, 'Y', AetherItems.Stick });
        ModLoader.addRecipe(new ItemStack(AetherItems.PickSkyroot, 1), new Object[] { "ZZZ", " Y ", " Y ", 'Z', AetherBlocks.Plank, 'Y', AetherItems.Stick });
        ModLoader.addRecipe(new ItemStack(AetherItems.AxeSkyroot, 1), new Object[] { "ZZ", "ZY", " Y", 'Z', AetherBlocks.Plank, 'Y', AetherItems.Stick });
        ModLoader.addRecipe(new ItemStack(AetherItems.ShovelSkyroot, 1), new Object[] { "Z", "Y", "Y", 'Z', AetherBlocks.Plank, 'Y', AetherItems.Stick });
        ModLoader.addRecipe(new ItemStack(AetherItems.SwordSkyroot, 1), new Object[] { "Z", "Z", "Y", 'Z', AetherBlocks.Plank, 'Y', AetherItems.Stick });
        ModLoader.addRecipe(new ItemStack(AetherItems.Bucket, 1, 0), new Object[] { "Z Z", " Z ", 'Z', AetherBlocks.Plank });
        ModLoader.addRecipe(new ItemStack(AetherItems.Stick, 4), new Object[] { "#", "#", '#', AetherBlocks.Plank });
        ModLoader.addRecipe(new ItemStack(Block.WORKBENCH, 1), new Object[] { "UU", "UU", 'U', AetherBlocks.Plank });
        ModLoader.addRecipe(new ItemStack(AetherBlocks.AmbrosiumTorch, 2), new Object[] { " Z", " Y", 'Z', AetherItems.AmbrosiumShard, 'Y', AetherItems.Stick });
        ModLoader.addRecipe(new ItemStack(AetherItems.Dart, 1, 0), new Object[] { "X", "Z", "Y", 'X', AetherItems.GoldenAmber, 'Z', AetherItems.Stick, 'Y', Item.FEATHER });
        ModLoader.addRecipe(new ItemStack(AetherItems.Dart, 8, 1), new Object[] { "XXX", "XZX", "XXX", 'X', new ItemStack(AetherItems.Dart, 1, 0), 'Z', new ItemStack(AetherItems.Bucket, 1, 2) });
        ModLoader.addRecipe(new ItemStack(AetherItems.WhiteCape, 1), new Object[] { "XX", "XX", "XX", 'X', new ItemStack(Block.WOOL, 1, 0) });
        ModLoader.addRecipe(new ItemStack(AetherItems.RedCape, 1), new Object[] { "XX", "XX", "XX", 'X', new ItemStack(Block.WOOL, 1, 14) });
        ModLoader.addRecipe(new ItemStack(AetherItems.BlueCape, 1), new Object[] { "XX", "XX", "XX", 'X', new ItemStack(Block.WOOL, 1, 11) });
        ModLoader.addRecipe(new ItemStack(AetherItems.BlueCape, 1), new Object[] { "XX", "XX", "XX", 'X', new ItemStack(Block.WOOL, 1, 3) });
        ModLoader.addRecipe(new ItemStack(AetherItems.BlueCape, 1), new Object[] { "XX", "XX", "XX", 'X', new ItemStack(Block.WOOL, 1, 9) });
        ModLoader.addRecipe(new ItemStack(AetherItems.YellowCape, 1), new Object[] { "XX", "XX", "XX", 'X', new ItemStack(Block.WOOL, 1, 4) });
        ModLoader.addRecipe(new ItemStack(AetherBlocks.Incubator, 1), new Object[] { "XXX", "XZX", "XXX", 'X', AetherBlocks.Holystone, 'Z', AetherBlocks.AmbrosiumTorch });
        ModLoader.addRecipe(new ItemStack(AetherBlocks.Freezer, 1), new Object[] { "XXX", "XZX", "YYY", 'X', AetherBlocks.Holystone, 'Z', AetherBlocks.Icestone, 'Y', AetherBlocks.Plank });
        ModLoader.addRecipe(new ItemStack(AetherBlocks.ZaniteBlock, 1), new Object[] { "XX", "XX", 'X', AetherItems.Zanite });
        ModLoader.addRecipe(new ItemStack(AetherItems.DartShooter, 1), new Object[] { "X", "X", "Y", 'X', AetherBlocks.Plank, 'Y', AetherItems.Zanite });
        ModLoader.addRecipe(new ItemStack(AetherItems.CloudParachute, 1), new Object[] { "UU", "UU", 'U', new ItemStack(AetherBlocks.Aercloud, 0) });
        ModLoader.addRecipe(new ItemStack(AetherItems.CloudParachuteGold, 1), new Object[] { "UU", "UU", 'U', new ItemStack(AetherBlocks.Aercloud, 2) });
        ModLoader.addRecipe(new ItemStack(Item.SADDLE, 1), new Object[] { "XXX", "XZX", 'X', Item.LEATHER, 'Z', Item.STRING });
        ModLoader.addRecipe(new ItemStack(AetherItems.NatureStaff, 1), new Object[] { "Y", "X", 'X', AetherItems.Stick, 'Y', AetherItems.Zanite });
        ModLoader.addRecipe(new ItemStack(AetherItems.GravititeHelmet, 1), new Object[] { "XXX", "X X", 'X', AetherBlocks.EnchantedGravitite });
        ModLoader.addRecipe(new ItemStack(AetherItems.GravititeBodyplate, 1), new Object[] { "X X", "XXX", "XXX", 'X', AetherBlocks.EnchantedGravitite });
        ModLoader.addRecipe(new ItemStack(AetherItems.GravititePlatelegs, 1), new Object[] { "XXX", "X X", "X X", 'X', AetherBlocks.EnchantedGravitite });
        ModLoader.addRecipe(new ItemStack(AetherItems.GravititeBoots, 1), new Object[] { "X X", "X X", 'X', AetherBlocks.EnchantedGravitite });
        ModLoader.addRecipe(new ItemStack(AetherItems.ZaniteHelmet, 1), new Object[] { "XXX", "X X", 'X', AetherItems.Zanite });
        ModLoader.addRecipe(new ItemStack(AetherItems.ZaniteChestplate, 1), new Object[] { "X X", "XXX", "XXX", 'X', AetherItems.Zanite });
        ModLoader.addRecipe(new ItemStack(AetherItems.ZaniteLeggings, 1), new Object[] { "XXX", "X X", "X X", 'X', AetherItems.Zanite });
        ModLoader.addRecipe(new ItemStack(AetherItems.ZaniteBoots, 1), new Object[] { "X X", "X X", 'X', AetherItems.Zanite });
        ModLoader.addShapelessRecipe(new ItemStack(AetherItems.DartShooter, 1, 1), new Object[] { new ItemStack(AetherItems.DartShooter, 1, 0), AetherItems.AechorPetal });
        ModLoader.addShapelessRecipe(new ItemStack(AetherItems.Zanite, 4), new Object[] { AetherBlocks.ZaniteBlock });
        ModLoader.addShapelessRecipe(new ItemStack(Item.INK_SACK, 2, 5), new Object[] { AetherBlocks.PurpleFlower });
        ModLoader.addRecipe(new ItemStack(Block.CHEST, 1), new Object[] { "PPP", "P P", "PPP", 'P', AetherBlocks.Plank });
        ModLoader.addRecipe(new ItemStack(Item.WOOD_DOOR), new Object[] { "PP", "PP", "PP", 'P', AetherBlocks.Plank });
        ModLoader.addRecipe(new ItemStack(Block.FENCE, 2), new Object[] { "SSS", "SSS", 'S', AetherItems.Stick });
        ModLoader.addRecipe(new ItemStack(Block.LADDER, 4), new Object[] { "S S", "SSS", "S S", 'S', AetherItems.Stick });
        ModLoader.addRecipe(new ItemStack(Block.JUKEBOX), new Object[] { "PPP", "PGP", "PPP", 'P', AetherBlocks.Plank, 'G', AetherBlocks.EnchantedGravitite });
        ModLoader.addRecipe(new ItemStack(AetherBlocks.Plank, 4), new Object[] { "L", 'L', AetherBlocks.Log });
        ModLoader.addRecipe(new ItemStack(AetherBlocks.Enchanter), new Object[] { "HHH", "HZH", "HHH", 'H', AetherBlocks.Holystone, 'Z', AetherItems.Zanite });
        ModLoader.addRecipe(new ItemStack(AetherItems.CloudParachute), new Object[] { "CC", "CC", 'C', new ItemStack(AetherBlocks.Aercloud, 1, 0) });
        ModLoader.addRecipe(new ItemStack(AetherItems.CloudParachuteGold), new Object[] { "CC", "CC", 'C', new ItemStack(AetherBlocks.Aercloud, 1, 2) });
        ModLoader.addRecipe(new ItemStack(AetherItems.LeatherGlove), new Object[] { "C C", 'C', Item.LEATHER });
        ModLoader.addRecipe(new ItemStack(AetherItems.IronGlove), new Object[] { "C C", 'C', Item.IRON_INGOT });
        ModLoader.addRecipe(new ItemStack(AetherItems.GoldGlove), new Object[] { "C C", 'C', Item.GOLD_INGOT });
        ModLoader.addRecipe(new ItemStack(AetherItems.DiamondGlove), new Object[] { "C C", 'C', Item.DIAMOND });
        ModLoader.addRecipe(new ItemStack(AetherItems.ZaniteGlove), new Object[] { "C C", 'C', AetherItems.Zanite });
        ModLoader.addRecipe(new ItemStack(AetherItems.GravititeGlove), new Object[] { "C C", 'C', AetherBlocks.EnchantedGravitite });
        ModLoader.addRecipe(new ItemStack(AetherItems.IronRing), new Object[] { " C ", "C C", " C ", 'C', Item.IRON_INGOT });
        ModLoader.addRecipe(new ItemStack(AetherItems.GoldRing), new Object[] { " C ", "C C", " C ", 'C', Item.GOLD_INGOT });
        ModLoader.addRecipe(new ItemStack(AetherItems.ZaniteRing), new Object[] { " C ", "C C", " C ", 'C', AetherItems.Zanite });
        ModLoader.addRecipe(new ItemStack(AetherItems.IronPendant), new Object[] { "SSS", "S S", " C ", 'S', Item.STRING, 'C', Item.IRON_INGOT });
        ModLoader.addRecipe(new ItemStack(AetherItems.GoldPendant), new Object[] { "SSS", "S S", " C ", 'S', Item.STRING, 'C', Item.GOLD_INGOT });
        ModLoader.addRecipe(new ItemStack(AetherItems.ZanitePendant), new Object[] { "SSS", "S S", " C ", 'S', Item.STRING, 'C', AetherItems.Zanite });
        ModLoader.addRecipe(new ItemStack(AetherBlocks.HolystoneStairs, 4), new Object[] { "  U", " UU", "UUU", 'U', new ItemStack(AetherBlocks.Holystone, 1, 0) });
        ModLoader.addRecipe(new ItemStack(AetherBlocks.MossyHolystoneStairs, 6), new Object[] { "  U", " UU", "UUU", 'U', new ItemStack(AetherBlocks.Holystone, 1, 2) });
        ModLoader.addRecipe(new ItemStack(AetherBlocks.IcestoneStairs, 4), new Object[] { "  U", " UU", "UUU", 'U', AetherBlocks.Icestone });
        ModLoader.addRecipe(new ItemStack(AetherBlocks.PlankStairs, 4), new Object[] { "  U", " UU", "UUU", 'U', AetherBlocks.Plank });
        ModLoader.addRecipe(new ItemStack(AetherBlocks.CarvedStairs, 6), new Object[] { "  U", " UU", "UUU", 'U', new ItemStack(AetherBlocks.DungeonStone, 1, 0) });
        ModLoader.addRecipe(new ItemStack(AetherBlocks.AngelicStairs, 6), new Object[] { "  U", " UU", "UUU", 'U', new ItemStack(AetherBlocks.DungeonStone, 1, 1) });
        ModLoader.addRecipe(new ItemStack(AetherBlocks.HellfireStairs, 6), new Object[] { "  U", " UU", "UUU", 'U', new ItemStack(AetherBlocks.DungeonStone, 1, 2) });
        ModLoader.addRecipe(new ItemStack(AetherBlocks.HolystoneFence, 6), new Object[] { "UUU", "UUU", 'U', new ItemStack(AetherBlocks.Holystone, 1, 0) });
        ModLoader.addRecipe(new ItemStack(AetherBlocks.MossyHolystoneFence, 6), new Object[] { "UUU", "UUU", 'U', new ItemStack(AetherBlocks.Holystone, 1, 2) });
        ModLoader.addRecipe(new ItemStack(AetherBlocks.IcestoneFence, 6), new Object[] { "UUU", "UUU", 'U', AetherBlocks.Icestone });
        ModLoader.addRecipe(new ItemStack(AetherBlocks.PlankFence, 6), new Object[] { "UUU", "UUU", 'U', AetherBlocks.Plank });
        ModLoader.addRecipe(new ItemStack(AetherBlocks.CarvedFence, 6), new Object[] { "UUU", "UUU", 'U', new ItemStack(AetherBlocks.DungeonStone, 1, 0) });
        ModLoader.addRecipe(new ItemStack(AetherBlocks.AngelicFence, 6), new Object[] { "UUU", "UUU", 'U', new ItemStack(AetherBlocks.DungeonStone, 1, 1) });
        ModLoader.addRecipe(new ItemStack(AetherBlocks.HellfireFence, 6), new Object[] { "UUU", "UUU", 'U', new ItemStack(AetherBlocks.DungeonStone, 1, 2) });
    }
}
